#!/bin/bash
#
# download-sounds.sh
#
# The 12 files in public/sounds/*.mp3 are PLACEHOLDERS — 1 second of silence,
# generated by ffmpeg so the audio system loads and the pipeline wires cleanly.
#
# Replace them with real CC0 / attribution-clear samples from freesound.org
# before any public broadcast. Keep the filenames exact — they're referenced
# directly by Fred's sound cue names in src/server/personas.ts and the overlay
# preload map in src/overlay/index.html.
#
# Required filenames:
#   rimshot.mp3
#   applause.mp3
#   sad-trombone.mp3
#   dramatic-sting.mp3
#   record-scratch.mp3
#   crickets.mp3
#   wrong-buzzer.mp3
#   cash-register.mp3
#   airhorn.mp3
#   laugh-track.mp3
#   boo.mp3
#   price-is-right-fail.mp3
#
# Search tips for freesound.org:
#   - Filter: "License > Creative Commons 0" (no attribution, safest)
#   - Duration: under 2s for most (rimshot, buzzer) — longer for laugh/applause
#   - Target sample rate: 44100 Hz, mono is fine
#   - Volume: don't normalize to peak — keep ~-10dB RMS or lower so the
#     overlay's 0.25 default volume plays cleanly
#
# After download, re-encode to MP3 (if source is WAV/OGG):
#   ffmpeg -i in.wav -codec:a libmp3lame -q:a 4 rimshot.mp3
#
# Regenerate placeholders (if needed):
#   cd public/sounds
#   for name in rimshot applause sad-trombone dramatic-sting record-scratch crickets \
#               wrong-buzzer cash-register airhorn laugh-track boo price-is-right-fail; do
#     ffmpeg -hide_banner -loglevel error -f lavfi -i anullsrc=r=44100:cl=mono \
#            -t 1 -q:a 9 -y "${name}.mp3"
#   done
#
# Nothing to execute right now — this file documents the replacement workflow.

echo "placeholder replacement workflow — see comments in this file"
echo "real sounds go in public/sounds/ with the exact filenames listed above"
